version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/home/node/app/
    container_name: api
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
